### ISSUE TITLE
Trouble generating quad dominant meshes

### ISSUE THREAD

**Issue by fire** [cgg-bern/quadwild-bimdf#10]
<img width="2032" alt="image" src="https://github.com/cgg-bern/quadwild-bimdf/assets/32321/ee4e8726-c99f-494d-a77d-ac9f198f8e06">

```
cmake . -B build -DWITH_GUROBI=0
cd build && make -j12 
./build/Build/bin/quadwild /Users/ernest.lee/Downloads/mesh.ply 2 config/prep_config/basic_setup.txt
./build/Build/bin/quad_from_patches /Users/ernest.lee/Downloads/mesh_rem_p0.obj 1000 config/main_config/flow_noalign_lemon.txt
```

**Comment by fire** [comment]
I'm not sure how to use quadwild-bimdf. All the models I've tested have holes in them.

**Comment by mheistermann** [comment]
Uff, that's a terrible outcome indeed, this is not normal.
Could you share the input mesh here? (I suppose it's just Suzanne with simple subdivision + triangulated?)

**Comment by mheistermann** [comment]
Running directly on the Suzanne mesh with the commands you specified I do get a sensible (even if not too great) mesh:

<img width="681" alt="Screenshot 2023-07-17 at 19 28 33" src="https://github.com/cgg-bern/quadwild-bimdf/assets/1302738/8f96bd13-8ae7-461f-9c63-232f11913c90">

**Comment by fire** [comment]
Here's what I have currently using your released build.

[Archive.zip](https://github.com/cgg-bern/quadwild-bimdf/files/12074151/Archive.zip)

<img width="2032" alt="image" src="https://github.com/cgg-bern/quadwild-bimdf/assets/32321/bbff5833-2141-4f2f-839d-f095145ac7a7">

I will report back using HEAD of this repo.

**Comment by fire** [comment]
Seems to work on 2f9ac3711232830bbdf64c891a525a781fcbd115.

Let me try the model I'll wanted to try and I'll close the issue.

**Comment by fire** [comment]
1. Download https://sketchfab.com/3d-models/female-body-base-for-rpg-a0be862b658d4b4e9aff461219281315#download
2. Export as ply named `mesh.ply`
3. Run commands

```
cmake . -B build -DWITH_GUROBI=0
cd build && make -j12 
./build/Build/bin/quadwild /Users/ernest.lee/Downloads/mesh.ply 2 config/prep_config/basic_setup.txt
./build/Build/bin/quad_from_patches /Users/ernest.lee/Downloads/mesh_rem_p0.obj 1000 config/main_config/flow_noalign_lemon.txt
```

4. Post archive.
5. Post Screenshots

<img width="2032" alt="Screenshot 2023-07-17 at 3 18 54 PM" src="https://github.com/cgg-bern/quadwild-bimdf/assets/32321/b9867d08-469b-45e8-adbb-6dfd8456aaaa">

<img width="2032" alt="image" src="https://github.com/cgg-bern/quadwild-bimdf/assets/32321/953c5e0f-3ee3-4be1-8100-b3155aad4270">

[female_body_for_rpg_quadwild_siggraph_2023.zip](https://github.com/cgg-bern/quadwild-bimdf/files/12074183/female_body_for_rpg_quadwild_siggraph_2023.zip)

**Comment by mheistermann** [comment]
I had a quick look at the input mesh:
It consists of many disconnected components, which will be meshed separately and thus not fit together at the borders. This is fine for parts like eyeballs and hair parts, but the body itself also is cut in various locations.

You can use "select all by trait | non manifold" in edit mode to find such seams.

<img width="412" alt="Screenshot 2023-07-18 at 10 42 39" src="https://github.com/cgg-bern/quadwild-bimdf/assets/1302738/b38b35ea-ea74-4af0-a600-8219d16091ff">

In this particular mesh, "merge by distance" already helps clean it up a bit and at least gives us the body in one piece.

However, after this repair, the face unfortunately does not quadrangulate well with default settings. A slight improvement can be had from changing the scale factor, other settings probably do more - but I didn't have time to experiment.

<img width="550" alt="Screenshot 2023-07-18 at 11 06 44" src="https://github.com/cgg-bern/quadwild-bimdf/assets/1302738/b6db9f97-af01-43d8-8da3-bee94e3e74db">

To get better results, we'd probably benefit from some manual guidance (marking sharp edges and guiding the cross field) - however unfortunately this is currently not implemented :(
