### ISSUE TITLE
Blender-plugins : Delete object in Blender gave warning.

### ISSUE THREAD

**Issue by ZAQraven** [cgg-bern/quadwild-bimdf#11]
**System Information** Operating system: Linux-6.3.12-200.fc38.x86_64-x86_64-with-glibc2.37 64 Bits

**Blender Version** 3.6.0, branch: blender-v3.6-release, commit: [2023-06-27](https://developer.blender.org/rBc7fc78b81ecb)

**QuadWild-BiMDF** :  (0.0.1)  (2023-05-19)

***************************************

While the addon is active. Blender sends a warning.
<pre>
Traceback (most recent call last):
  File "/home/zaqraven/.config/blender/3.6/scripts/addons/quadwild-bimdf/__init__.py", line 276, in poll
    return obj.type == 'MESH'
AttributeError: 'NoneType' object has no attribute 'type'
</pre>

**Comment by mheistermann** [comment]
Thanks for the bug report, fixed 👍
