### ISSUE TITLE
Vector subcript out of range while running "quadrangulate"

### ISSUE THREAD

**Issue by hongbin-y** [cgg-bern/quadwild-bimdf#15]
![image](https://github.com/cgg-bern/quadwild-bimdf/assets/31581382/17a8d8f9-ebe7-41ef-8cbd-1f308e698b7a)
And the stack info is :
![image](https://github.com/cgg-bern/quadwild-bimdf/assets/31581382/48d376c7-5ac5-4275-8057-e1ceea0b4388)
My test model is non-manfild:

[House.zip](https://github.com/cgg-bern/quadwild-bimdf/files/14083198/House.zip)

**Comment by mheistermann** [comment]
Hi! Thanks for the bug report, I'll fix this crash (this can get triggered too for meshes with boundary in debug builds).

However afterwards it still won't produce a non-manifold quad mesh, that's unfortunately not supported (and non-trivial to 
add).
The QuadWild preprocessing (from the original QuadWild, not my code) *might* try to fix non-manifoldness, I'm not sure - but even if so, depending on the input the results may not be what you expect.

**Comment by mheistermann** [comment]
Fixed! I'm getting *some* mesh out, not sure how useful for your purposes.

<img width="816" alt="Screenshot 2024-01-29 at 13 22 36" src="https://github.com/cgg-bern/quadwild-bimdf/assets/1302738/97df9639-049d-401a-9351-591c26b9b80d">

The issues most likely stem from the non-manifoldness.
