### ISSUE TITLE
Error compiling on Windows

### ISSUE THREAD

**Issue by ksami** [cgg-bern/quadwild-bimdf#21]
Hi, I tried compiling the latest commit on main for Windows and got the following error
```
D:\a\quadwild-bimdf\quadwild-bimdf\libs\satsuma\src\libsatsuma/Problems/CostFunction.hh(73,60): error : no member named 'back_inserter' in namespace 'std' [D:\a\quadwild-bimdf\quadwild-bimdf\build\libs\satsuma\src\satsuma.vcxproj]
```
I think it might be fixed by adding `#include <iterator>` similar to https://github.com/erengy/anitomy/issues/2#issuecomment-124042738

Full log: https://github.com/ksami/quadwild-bimdf/actions/runs/10843719395/job/30091338230#step:3:2210

**Comment by ksami** [comment]
Just noticed this was already fixed at https://github.com/cgg-bern/libSatsuma/commit/becb12fa3bd3ba22267e51490732befdfb595c10

**Comment by mheistermann** [comment]
Good catch, I updated the submodule to the latest satsuma version: https://github.com/cgg-bern/quadwild-bimdf/commit/cbda68e5deddf9d0e24c24382852f37a6eb2a630
