### ISSUE TITLE
Provide blender plugin

### ISSUE THREAD

**Issue by mheistermann** [cgg-bern/quadwild-bimdf#7]
Easiest way might be just calling the CLI binaries.

**Comment by mheistermann** [comment]
Blender plugin status: https://github.com/cgg-bern/quadwild-bimdf/issues/12#issuecomment-1638562295
(TL;DR: I would like to work on this but will not have time for this in the next few months).

**Comment by fire** [comment]
Can you think of any approaches to keep the uv mapping?

**Comment by mheistermann** [comment]
The current quadwild implementation does not support keeping UVs, but in Blender you could try to use the [Data Transfer modifier](https://docs.blender.org/manual/en/latest/modeling/modifiers/modify/data_transfer.html).

**Comment by mheistermann** [comment]
Two independent Blender plugins have already been published:

[quadwild-wrapper](https://github.com/dairin0d/quadwild-wrapper) by @dairin0d
as well as
[QRemeshify](https://github.com/ksami/QRemeshify/) ([Gumroad page](https://ksami.gumroad.com/l/QRemeshify)) by @ksami 

Thanks @dairin0d and @ksami for your work! I'm happy end users can now easily try QuadWild now :-) Think the resulting feedback will be super valuable for our continued research.
